import { useState } from 'react';
import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer';
import { useStudent } from '../../hooks/useStudent';
import { MILESTONES } from '../../data/milestones';
import { DOMAINS } from '../../data/domains';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 10 },
  header: { marginBottom: 20 },
  title: { fontSize: 20, fontFamily: 'Helvetica-Bold', marginBottom: 4 },
  subtitle: { fontSize: 10, color: '#666', marginBottom: 12 },
  line: { borderBottomWidth: 1, borderBottomColor: '#ddd', marginBottom: 12 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 13, fontFamily: 'Helvetica-Bold', marginBottom: 6 },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  domainCard: { padding: 8, borderWidth: 1, borderColor: '#ddd', borderRadius: 4, marginBottom: 6 },
  domainName: { fontSize: 11, fontFamily: 'Helvetica-Bold', marginBottom: 2 },
  milestone: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 2, fontSize: 9 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', fontSize: 8, color: '#bbb' },
});

function WeeklyReportDocument({ student, age, domainStats, milestoneStatus }) {
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{student.firstName}'s Weekly Report</Text>
          <Text style={styles.subtitle}>
            Age {age.years}yr {age.months}mo | {student.schoolName} | {dateStr}
          </Text>
          <View style={styles.line} />
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Domain Scores</Text>
          {domainStats.map(d => (
            <View key={d.id} style={styles.domainCard}>
              <View style={styles.row}>
                <Text style={styles.domainName}>{d.icon} {d.name}</Text>
                <Text>{d.childScore}% vs age | {d.comparison5yr.us}% US | {d.comparison5yr.uk}% UK | {d.comparison5yr.nz}% NZ</Text>
              </View>
              <Text style={{ fontSize: 9, color: '#666' }}>
                {d.mastered} mastered, {d.proficient} proficient, {d.inProgress} in progress / {d.total} total
              </Text>
            </View>
          ))}
        </View>

        {DOMAINS.map(domain => {
          const milestones = MILESTONES.filter(m => m.domainId === domain.id);
          const active = milestones.filter(m => {
            const s = milestoneStatus[m.id];
            return s && s.status !== 'not-started';
          });
          if (active.length === 0) return null;
          return (
            <View key={domain.id} style={styles.section} wrap={false}>
              <Text style={styles.sectionTitle}>{domain.icon} {domain.name} — Active Milestones</Text>
              {active.map(m => {
                const s = milestoneStatus[m.id] || {};
                return (
                  <View key={m.id} style={styles.milestone}>
                    <Text>{m.id} {m.name}</Text>
                    <Text>{s.status} ({s.progress}%)</Text>
                  </View>
                );
              })}
            </View>
          );
        })}

        <Text style={styles.footer}>Generated by Alpha Learning Dashboard | {dateStr}</Text>
      </Page>
    </Document>
  );
}

export default function WeeklyReportButton() {
  const { student, age, domainStats, milestoneStatus } = useStudent();
  const [generating, setGenerating] = useState(false);

  async function handleExport() {
    setGenerating(true);
    try {
      const blob = await pdf(
        <WeeklyReportDocument student={student} age={age} domainStats={domainStats} milestoneStatus={milestoneStatus} />
      ).toBlob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${student.firstName}-weekly-report-${new Date().toISOString().split('T')[0]}.pdf`;
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setGenerating(false);
    }
  }

  return (
    <button
      onClick={handleExport}
      disabled={generating}
      className="text-xs px-3 py-1.5 rounded-lg border border-literacy text-literacy hover:bg-literacy/10 transition-colors disabled:opacity-50"
    >
      {generating ? 'Generating...' : '\u{1F4C4} Export Weekly Report PDF'}
    </button>
  );
}

